# Generated by Django 3.2.4 on 2021-06-25 11:13

from django.db import migrations, models  # importing migrations and models modules from django.db modules(library or packages)


class Migration(migrations.Migration):      # Migration class inherits Migration class from migrations module

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=64)),
                ('destination', models.CharField(max_length=64)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
